project:
  type: website
  output-dir: docs

website:
  title: "MACROPHEST-LAB"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research lines
        menu:
        - text: "Overview"
          href: projects.qmd
        - text: "Data science"
          href: research_data.qmd
        - text: "Thermal tolerance and performance"
          href: research_thermal.qmd
        - text: "Spatial and temporal forecasts"
          href: research_forecast.qmd
        - text: "Interaction networks"
          href: research_networks.qmd
      - text: Team
        href: team.qmd
      - text: Publications
        href: publications.qmd
      - text: News
        href: news.qmd
      - text: About
        href: about.qmd
    page-navigation: true
format:
  html:
    theme: sandstone
    toc: false
    include-after-body: footer.html

editor: visual

